import Head from 'next/head'

export function getStaticProps() {
  return {
    props: { posts: {} }
  };
}

export default function Home({ posts }) {
  // The below stuff is like simple html. Kinda crazy how anybody would think this is hard.
  // Anyways, what's crazy is gonna be the posts.
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>HMP Blog 2022</h1>
      <h2>Introduction</h2>

      <p>
        Hello, my name is Vu Huy Minh Pham.
        Thank you so much for your time, taking a visit to my dynamic blog web page.
        You might find some information useful here.
        <br />
        The rest of the blog is mostly about things that I am doing with passion! :D
        <br />
        And as well as some personal preferences.
      </p>

      <h2>My Feed</h2>
      // TODO add a newest feed update system. It would be simple if the database request stuff gets you stuff in order.
      <ul>
      </ul>
    </div>
  )
}
